// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUjDGpGLTJY2o8Tg4dgPxjc1tJdla9k_E',
    appId: '1:465357739001:web:c0ce58acd5294e02af6328',
    messagingSenderId: '465357739001',
    projectId: 'fir-firstapp-5fc2d',
    authDomain: 'fir-firstapp-5fc2d.firebaseapp.com',
    storageBucket: 'fir-firstapp-5fc2d.appspot.com',
    measurementId: 'G-PQ77N4G2S7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_3D1rVnA5z7hs6fjb7SOI8QJ5QV6kSkg',
    appId: '1:465357739001:android:5ae1ae625ee081f4af6328',
    messagingSenderId: '465357739001',
    projectId: 'fir-firstapp-5fc2d',
    storageBucket: 'fir-firstapp-5fc2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMfNoSfTr7RRrNxHdIu4XHBfJXGBud2_c',
    appId: '1:465357739001:ios:a35e9e626923b41faf6328',
    messagingSenderId: '465357739001',
    projectId: 'fir-firstapp-5fc2d',
    storageBucket: 'fir-firstapp-5fc2d.appspot.com',
    iosClientId: '465357739001-5cmtn8a66tcno6lpfm3ml9kjr6jveobi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMfNoSfTr7RRrNxHdIu4XHBfJXGBud2_c',
    appId: '1:465357739001:ios:a35e9e626923b41faf6328',
    messagingSenderId: '465357739001',
    projectId: 'fir-firstapp-5fc2d',
    storageBucket: 'fir-firstapp-5fc2d.appspot.com',
    iosClientId: '465357739001-5cmtn8a66tcno6lpfm3ml9kjr6jveobi.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );
}
